version: '3.9'
services:
    mysql:
        image: mysql
        ports:
            - '3306:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=admin
            - MYSQL_DATABASE=proyecto
            - MYSQL_PASSWORD=admin
            - MYSQL_USER=admin
        volumes:
            - './mysql_data:/var/lib/mysql'
        container_name: mysqldb

