

CREATE TABLE usuarios (
    id_usuario INT NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(50),
    apellidos VARCHAR(50),
    email VARCHAR(50),
    password VARCHAR(50),
    PRIMARY KEY (id_usuario)
);

INSERT INTO usuarios (nombre, apellidos, email, password) VALUES
('Gregor', 'Ashment', 'gashment0@loc.gov', 'J9vP7wR1'),
('pepito', 'perez perez', 'pepito@per.mail', 'T5qM2zS3'),
('Olive', 'Crallan', 'ocrallan1@arizona.edu', 'B8fK4xL6'),
('Hashim', 'Osgerby', 'hosgerby2@ow.ly', 'Y7uN3wJ9'),
('Kaycee', 'Stronack', 'kstronack3@eventbrite.com', 'M4tW8dR5'),
('Nick', 'Ions', 'nions4@army.mil', 'L1hV9cP3'),
('Ruben', 'Scoggins', 'rscoggins5@comcast.net', 'Q2rJ8wK6'),
('Cecil', 'Hustings', 'chustings6@tinyurl.com', 'P7dM4yV2'),
('Baron', 'Colhoun', 'bcolhoun7@guardian.co.uk', 'X9lF5bR8'),
('Flin', 'Brantzen', 'fbrantzen8@statcounter.com', 'R6vT3pN1'),
('Moishe', 'Fealey', 'mfealey9@g.co', 'K8jH1xP7'),
('Poppy', 'Brainsby', 'pbrainsbya@about.com', 'N4wQ2rT9'),
('Eb', 'Flament', 'eflamentb@uiuc.edu', 'Z3vM7xR8'),
('Denis', 'Golledge', 'dgolledgec@so-net.ne.jp', 'F6yL2rW9'),
('Vally', 'Astridge', 'vastridged@nytimes.com', 'W5qN8pR3'),
('Aurora', 'Shattock', 'ashattocke@npr.org', 'T9hM2vF6'),
('Boonie', 'Decruse', 'bdecrusef@so-net.ne.jp', 'J4kL9rP2'),
('Deane', 'Fairtlough', 'dfairtloughg@opensource.org', 'Y3vN6pT7'),
('Darnell', 'Benedicte', 'dbenedicteh@godaddy.com', 'M8rK4wQ2'),
('Syman', 'Kedward', 'skedwardi@timesonline.co.uk', 'L7xN2pF9'),
('Wilhelm', 'Bartolomeo', 'wbartolomeoj@jiathis.com', 'P9vR3yL6'),
('Tamra', 'Trymme', 'ttrymmek@marketwatch.com', 'R4wK8nP1'),
('Tandi', 'Hartil', 'thartill@photobucket.com', 'F2vN6rW9'),
('Sophie', 'Stanner', 'sstannerm@latimes.com', 'J5kL8pQ3'),
('Marieann', 'Cornuau', 'mcornuaun@va.gov', 'T9wR2vF7'),
('Amelie', 'Jennaroy', 'ajennaroyo@facebook.com', 'N4pM6yL2'),
('Malvin', 'Copnar', 'mcopnarp@is.gd', 'Q8rK5wJ3'),
('Nancy', 'Fagge', 'nfaggeq@wikipedia.org', 'P7xL2vF9'),
('Brier', 'Moisey', 'bmoiseyr@istockphoto.com', 'R6kN4wQ2'),
('Alexei', 'M\'\'Quhan', 'amquhans@stanford.edu', 'T9vM2xL5'),
('Orlando', 'Klimpke', 'oklimpket@bravesites.com', 'L3rP8yN6'),
('Tammi', 'Androck', 'tandrocku@wikispaces.com', 'F4wN7rK2'),
('Torey', 'Trim', 'ttrimv@tinyurl.com', 'Q5pM9xL1'),
('Opaline', 'Scandrett', 'oscandrettw@patch.com', 'J2vR6yK8'),
('Adara', 'Caps', 'acapsx@over-blog.com', 'N7pL3wF5'),
('Lorrie', 'Kleiner', 'lkleinery@chron.com', 'T4kM8xP2'),
('Cristie', 'Kanter', 'ckanterz@biglobe.ne.jp', 'P9rN3vL6'),
('Corbie', 'Ricci', 'cricci10@slideshare.net', 'Q2xL7wM8'),
('Haleigh', 'Atrill', 'hatrill11@ameblo.jp', 'R6vK3pN1'),
('Marijn', 'Atchly', 'matchly12@clickbank.net', 'F8yN2wL5'),
('Amery', 'Taffarello', 'ataffarello13@admin.ch', 'T3rP7kL6'),
('Sallyann', 'Ferraraccio', 'sferraraccio14@hostgator.com', 'N9wL2pF8'),
('Sarena', 'Proudler', 'sproudler15@apache.org', 'J4xM8rP2'),
('Torin', 'Andreazzi', 'tandreazzi16@posterous.com', 'P7vK2xL5'),
('Ileane', 'Treadger', 'itreadger17@amazon.de', 'R3nM6pQ8'),
('Melamie', 'McVrone', 'mmcvrone18@prlog.org', 'L2kP9vF4'),
('Rahel', 'Hatto', 'rhatto19@pagesperso-orange.fr', 'Q6xN3wL5'),
('Ysabel', 'Glew', 'yglew1a@bloglovin.com', 'J8vK2rP1'),
('Base', 'Seagrove', 'bseagrove1b@timesonline.co.uk', 'F5wN6xL2'),
('Billie', 'Manktelow', 'bmanktelow1c@geocities.jp', 'R9pM4vL7'),
('Claybourne', 'Kolczynski', 'ckolczynski1d@clickbank.net', 'N2xL8pF5');
